package org.scaffold.common;

import org.scaffold.common.security.jwt.Extract;

/**
 * Hello world!
 *
 */
public class App 
{
    public static void main( String[] args )
    {
        Extract extract=new Extract();
        extract.extract("eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJhZG1pbiIsInNjb3BlIjpbImFsbCJdLCJyb2xlcyI6W3siY3JlYXRlciI6IjIiLCJjcmVhdGVEYXRlIjpudWxsLCJvcGVyYXRpb25EYXRlIjpudWxsLCJyZW1hcmsiOm51bGwsInN0YXR1cyI6MSwiaWQiOjEsInJvbGVObyI6IjAxIiwicm9sZU5hbWUiOiLnrqHnkIblkZgiLCJpc0hhbmRsZXIiOjAsInRlbXBGbGFnIjowLCJ0ZW1wU3RhcnREYXRlIjpudWxsLCJ0ZW1wRW5kRGF0ZSI6bnVsbH1dLCJtZW51cyI6W3siY3JlYXRlciI6bnVsbCwiY3JlYXRlRGF0ZSI6bnVsbCwib3BlcmF0aW9uRGF0ZSI6bnVsbCwicmVtYXJrIjpudWxsLCJzdGF0dXMiOjEsImlkIjoyLCJwYXJlbnRJZCI6MSwibWVudU5hbWUiOiLmt7vliqDnlLXog73ooagiLCJhcHBObyI6bnVsbCwiaXNMZWFmIjoxLCJtZW51VXJsIjpudWxsLCJpbWdTcmMiOm51bGwsInNvcnRPcmRlciI6Mn0seyJjcmVhdGVyIjpudWxsLCJjcmVhdGVEYXRlIjpudWxsLCJvcGVyYXRpb25EYXRlIjpudWxsLCJyZW1hcmsiOm51bGwsInN0YXR1cyI6MSwiaWQiOjEsInBhcmVudElkIjpudWxsLCJtZW51TmFtZSI6Iui1hOS6p-euoeeQhiIsImFwcE5vIjpudWxsLCJpc0xlYWYiOjAsIm1lbnVVcmwiOm51bGwsImltZ1NyYyI6bnVsbCwic29ydE9yZGVyIjoxfV0sImV4cCI6MTY0ODE5OTcxOSwiYXV0aG9yaXRpZXMiOlsiMDEiXSwianRpIjoiYWM4ZTY4YTAtY2I0Yy00NzdmLWFjZTUtOTQzNWViMmQwYzJjIiwiZGVwdHMiOltdLCJjbGllbnRfaWQiOiJ3ZWIifQ.s0FjF5loQJpiH0nGsqdpcfkxayLlyeP3-MzVlv55fE7HiiqXnE92nWyFWTbU3DQL2VgnynnOxTsIxCtiPSRrvY0fcPKuu2jecaE29eDxIRdmOhX3DOSME_CWL83-F0Bkc0whVLYZEw4yHqRs9TIZ6kJNt2gI8MQgw1-4-FekEILI_rNVdT33UcOc8IwEAlNcGzbavGJGJ35oDiV8MkD-FM9h5qqrpPjwJNwAKix7Brhs7a7i2qOtCJmV2HnWEkvIWnQqOP-4AHsrc5ImTI9iYRXHme2Z7RDEJJkOWrSNAbVq3Xp1FYy74WKJXGFnsDMMwSqpUjMr_I6Ii24cUsnYUA");
    }
}
